FROM python 

RUN pip install pika
RUN pip install redis
RUN pip install minio

WORKDIR /app

COPY *.py /app/
COPY transaction.json /app/
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD [ "/usr/bin/supervisord" ]

#ENTRYPOINT [ "python", "consumer.py" ]